# Generated by Django 4.0.5 on 2022-07-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota', '0004_alter_nota_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='subtitulo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nota',
            name='imagen',
            field=models.ImageField(blank=True, default='imagen_nota/rick.jpg', null=True, upload_to='imagen_nota'),
        ),
    ]
