# Generated by Django 4.0.5 on 2022-07-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota', '0005_nota_subtitulo_alter_nota_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagen_nota'),
        ),
    ]
