# Generated by Django 4.0.5 on 2022-07-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota', '0006_alter_nota_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='imagen',
            field=models.ImageField(blank=True, default='imagen_nota/rick.jpg', null=True, upload_to='imagen_nota'),
        ),
    ]
