# Generated by Django 4.0.5 on 2022-07-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota', '0008_alter_nota_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='imagen',
            field=models.ImageField(default=1, upload_to='imagen_nota'),
            preserve_default=False,
        ),
    ]
